export const metadata = { title: "Terms of Service" };

export default function Terms() {
  return (
    <div className="prose prose-slate mx-auto max-w-3xl px-4 py-12 prose-headings:font-semibold">
      <h1>Terms of Service</h1>
      <p>
        AppealKit (&quot;the Service&quot;) provides automated document drafting tools. By using
        the Service you agree to these terms.
      </p>
      <h2>Not legal advice</h2>
      <p>
        The Service is not a law firm and does not provide legal advice, legal opinions, or
        legal representation. Documents generated by the Service are drafts prepared from
        information you provide; you are solely responsible for reviewing, editing, and
        deciding whether and how to use them. No attorney-client relationship is created.
      </p>
      <h2>No guarantee of outcome</h2>
      <p>
        Appeals, rebuttals, and similar processes are decided by third parties. We make no
        representation or warranty about the outcome of any matter in which a generated
        document is used.
      </p>
      <h2>Payments and refunds</h2>
      <p>
        Purchases are one-time payments processed by Stripe. If a technical failure prevents
        you from receiving a document you paid for, contact us at support@appealkits.com with
        your receipt and we will regenerate it or refund you.
      </p>
      <h2>Acceptable use</h2>
      <p>
        You agree not to use the Service to produce false statements of fact, documents for
        fraudulent purposes, or content that violates any law.
      </p>
      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, the Service&apos;s total liability for any
        claim arising from use of the Service is limited to the amount you paid for the
        document giving rise to the claim.
      </p>
    </div>
  );
}
